# Generated by Django 4.1.3 on 2022-11-24 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adaptapp', '0002_alter_category_id_alter_positionincomp_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='positionincomp',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='priority',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tasktype',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
