# Generated by Django 4.1.3 on 2022-11-24 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adaptapp', '0003_alter_category_id_alter_positionincomp_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userplan',
            name='deadline',
            field=models.DateField(null=True),
        ),
    ]
